name: Ruby Lint and Review dog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.3'  # Specify your Ruby version here
        bundler-cache: true  # Automatically cache and install gems

    - name: Run RuboCop
      run: bundle exec rubocop app/ # tạm thời chỉ chạy cho thư mục app sau này sẽ update lại

  reviewdog:
    name: Reviewdog
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.3'
        bundler-cache: true

    - name: Run RuboCop with Reviewdog
      uses: reviewdog/action-rubocop@v2
      with:
        rubocop_version: gemfile
        rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        fail_on_error: false
        filter_mode: nofilter
        rubocop_flags: '--format json'  # This flag enables auto-correction suggestions
        level: warning
        suggest_and_apply: true  # This enables automatic suggestion application