name: Ruby Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.3'  # Specify your Ruby version here
        bundler-cache: true  # Automatically cache and install gems

    - name: Run RuboCop
      run: bundle exec rubocop app/